// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bookpb.proto

package bookpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BookInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=Author,proto3" json:"Author,omitempty"`
	Year                 int32    `protobuf:"varint,4,opt,name=Year,proto3" json:"Year,omitempty"`
	Size                 int32    `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	Rate                 float32  `protobuf:"fixed32,6,opt,name=Rate,proto3" json:"Rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookInfo) Reset()         { *m = BookInfo{} }
func (m *BookInfo) String() string { return proto.CompactTextString(m) }
func (*BookInfo) ProtoMessage()    {}
func (*BookInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbf59d96e76a6885, []int{0}
}

func (m *BookInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookInfo.Unmarshal(m, b)
}
func (m *BookInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookInfo.Marshal(b, m, deterministic)
}
func (m *BookInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookInfo.Merge(m, src)
}
func (m *BookInfo) XXX_Size() int {
	return xxx_messageInfo_BookInfo.Size(m)
}
func (m *BookInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BookInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BookInfo proto.InternalMessageInfo

func (m *BookInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *BookInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *BookInfo) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *BookInfo) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *BookInfo) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func init() {
	proto.RegisterType((*BookInfo)(nil), "bookpb.BookInfo")
}

func init() {
	proto.RegisterFile("bookpb.proto", fileDescriptor_fbf59d96e76a6885)
}

var fileDescriptor_fbf59d96e76a6885 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xca, 0xcf, 0xcf,
	0x2e, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x5a, 0x18, 0xb9,
	0x38, 0x9c, 0xf2, 0xf3, 0xb3, 0x3d, 0xf3, 0xd2, 0xf2, 0x85, 0xf8, 0xb8, 0x98, 0x3c, 0x53, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x98, 0x83, 0x98, 0x3c, 0x53, 0x84, 0x44, 0xb8, 0x58, 0x43, 0x32, 0x4b,
	0x72, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x31, 0x2e, 0x36, 0xc7,
	0xd2, 0x92, 0x8c, 0xfc, 0x22, 0x09, 0x66, 0xb0, 0x30, 0x94, 0x27, 0x24, 0xc4, 0xc5, 0x12, 0x99,
	0x9a, 0x58, 0x24, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x66, 0x83, 0xc4, 0x82, 0x33, 0xab,
	0x52, 0x25, 0x58, 0x21, 0x62, 0x20, 0x36, 0x48, 0x2c, 0x28, 0xb1, 0x24, 0x55, 0x82, 0x4d, 0x81,
	0x51, 0x83, 0x29, 0x08, 0xcc, 0x4e, 0x62, 0x03, 0xbb, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x6b, 0xd1, 0x0e, 0xd9, 0xa5, 0x00, 0x00, 0x00,
}
